/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of Pedigrem.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PedigremPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// ../src/parser.ts
function parseChildrenExpression(expr) {
  const result = [];
  let currentToken = "";
  let bracketDepth = 0;
  for (let i = 0; i < expr.length; i++) {
    const char = expr[i];
    if (char === "[") {
      bracketDepth++;
      currentToken += char;
    } else if (char === "]") {
      bracketDepth--;
      currentToken += char;
    } else if (char === "," && bracketDepth === 0) {
      if (currentToken.trim()) {
        result.push(parseChildToken(currentToken.trim()));
      }
      currentToken = "";
    } else {
      currentToken += char;
    }
  }
  if (currentToken.trim()) {
    result.push(parseChildToken(currentToken.trim()));
  }
  return result;
}
function parseChildToken(token) {
  if (token.startsWith("[[") && token.endsWith("]]")) {
    const names = token.slice(2, -2).split(",").map((n) => n.trim()).filter(Boolean);
    return { type: "dizygotic", children: names };
  } else if (token.startsWith("[") && token.endsWith("]")) {
    const names = token.slice(1, -1).split(",").map((n) => n.trim()).filter(Boolean);
    return { type: "monozygotic", children: names };
  } else {
    return { type: "single", name: token };
  }
}
function parseDSL(dsl) {
  const individuals = /* @__PURE__ */ new Map();
  const relationships = [];
  const legends = [];
  const lines = dsl.split(/\r?\n/).map((l) => l.trim());
  for (let lineNum = 1; lineNum <= lines.length; lineNum++) {
    const line = lines[lineNum - 1];
    if (!line || line.startsWith("%") || line.startsWith("#")) {
      continue;
    }
    if (line.startsWith("!")) {
      const parts = line.slice(1).trim().split(/\s+/);
      const status2 = parts[0];
      const description = parts.slice(1).join(" ");
      if (!status2 || !description) {
        throw new Error(`Invalid legend on line ${lineNum}: ${line}`);
      }
      legends.push({ status: status2, description });
      continue;
    }
    if (line.startsWith("~")) {
      const content = line.slice(1).trim();
      const parts = content.split(">");
      const left = parts[0].trim();
      const right = parts[1] ? parts[1].trim() : "";
      const opMatch = left.match(/([-=\/|])/);
      if (!opMatch) {
        throw new Error(`Invalid relationship format on line ${lineNum}: ${line}`);
      }
      const op = opMatch[1];
      const opIndex = left.indexOf(op);
      const parent1 = left.slice(0, opIndex).trim();
      const parent2 = left.slice(opIndex + 1).trim();
      if (!parent1 || !parent2) {
        throw new Error(`Missing parents in relationship on line ${lineNum}: ${line}`);
      }
      let isChildless = false;
      let isInfertile = false;
      let children = [];
      if (parts.length > 1) {
        if (right === "" || right === "choice") {
          isChildless = true;
        } else if (right === "*") {
          isChildless = true;
          isInfertile = true;
        } else {
          children = parseChildrenExpression(right);
        }
      }
      relationships.push({
        parent1,
        parent2,
        op,
        children,
        isChildless,
        isInfertile
      });
      continue;
    }
    let parsedLine = line;
    let label = void 0;
    const labelMatch = line.match(/\[label:([^\]]+)\]/);
    if (labelMatch) {
      label = labelMatch[1];
      parsedLine = line.replace(labelMatch[0], "").trim();
    }
    const tokens = parsedLine.split(/\s+/);
    const id = tokens[0];
    const sex = tokens[1];
    const status = tokens[2];
    if (!id || !["M", "F", "U", "A"].includes(sex) || !["Af", "UAf", "Ca", "XCa", "Unk"].includes(status)) {
      throw new Error(`Invalid individual definition on line ${lineNum}: ${line}`);
    }
    const ind = { id, sex, status };
    if (label) {
      ind.label = label;
    }
    for (let i = 3; i < tokens.length; i++) {
      const attr = tokens[i];
      if (/^\d/.test(attr)) {
        ind.age = attr;
      } else if (attr === "index" || attr === "proband") {
        ind.isIndex = true;
      } else if (attr === "dead") {
        ind.isDeceased = true;
      } else if (attr === "adopted-in") {
        ind.adopted = "in";
      } else if (attr === "adopted-out") {
        ind.adopted = "out";
      } else if (attr === "preg") {
        ind.isPreg = true;
      } else if (attr === "misc") {
        ind.isMisc = true;
      } else if (attr === "induced") {
        ind.isInduced = true;
      } else if (attr === "sb") {
        ind.isSb = true;
      }
    }
    individuals.set(id, ind);
  }
  return { individuals, relationships, legends };
}

// ../src/theme.ts
var theme = {
  ink: "#111827",
  // Off-black for premium look, standard is black
  surface: "#ffffff",
  // White background
  gray: "#9ca3af",
  // Color for helper/grid markings if any
  text: "#1f2937"
  // Deep gray for text labels
};

// ../src/layout.ts
var ROW_HEIGHT_PX = 90;
var NODE_GAP_PX = 60;
var SYMBOL_PX = 24;
var MARGIN_X = 60;
var MARGIN_Y = 40;
function layoutDiagram(diagram) {
  const nodes = [];
  const parentRelMap = /* @__PURE__ */ new Map();
  for (const rel of diagram.relationships) {
    for (const group of rel.children) {
      if (group.type === "single") {
        parentRelMap.set(group.name, rel);
      } else {
        for (const name of group.children) {
          parentRelMap.set(name, rel);
        }
      }
    }
  }
  const genMemo = /* @__PURE__ */ new Map();
  function getGen(id) {
    if (genMemo.has(id))
      return genMemo.get(id);
    const rel = parentRelMap.get(id);
    if (!rel) {
      genMemo.set(id, 0);
      return 0;
    }
    const g = 1 + Math.max(getGen(rel.parent1), getGen(rel.parent2));
    genMemo.set(id, g);
    return g;
  }
  const row = /* @__PURE__ */ new Map();
  for (const id of diagram.individuals.keys()) {
    row.set(id, getGen(id));
  }
  for (const rel of diagram.relationships) {
    const r1 = row.get(rel.parent1) ?? 0;
    const r2 = row.get(rel.parent2) ?? 0;
    const maxR = Math.max(r1, r2);
    row.set(rel.parent1, maxR);
    row.set(rel.parent2, maxR);
  }
  const relationshipId = (rel) => {
    return [rel.parent1, rel.parent2].sort().join("-");
  };
  const coupleByPartner = /* @__PURE__ */ new Map();
  for (const rel of diagram.relationships) {
    coupleByPartner.set(rel.parent1, rel);
    coupleByPartner.set(rel.parent2, rel);
  }
  const x = /* @__PURE__ */ new Map();
  let cursor = MARGIN_X;
  const slot = () => {
    const at = cursor;
    cursor += SYMBOL_PX + NODE_GAP_PX;
    return at;
  };
  const placed = /* @__PURE__ */ new Set();
  function placeNode(id) {
    if (x.has(id))
      return x.get(id);
    placed.add(id);
    const rel = coupleByPartner.get(id);
    if (rel) {
      return placeRelationship(rel);
    }
    const at = slot();
    x.set(id, at);
    return at;
  }
  function placeRelationship(rel) {
    const key = relationshipId(rel);
    if (x.has(key))
      return x.get(key);
    x.set(key, MARGIN_X);
    const kidsList = [];
    for (const group of rel.children) {
      if (group.type === "single") {
        kidsList.push(group.name);
      } else {
        kidsList.push(...group.children);
      }
    }
    const kidXs = kidsList.map(placeNode);
    const half = (SYMBOL_PX + NODE_GAP_PX) / 2;
    let mid;
    if (kidXs.length > 0) {
      mid = (Math.min(...kidXs) + Math.max(...kidXs)) / 2;
      x.set(rel.parent1, mid - half);
      x.set(rel.parent2, mid + half);
    } else {
      const p1x = slot();
      const p2x = slot();
      x.set(rel.parent1, p1x);
      x.set(rel.parent2, p2x);
      mid = (p1x + p2x) / 2;
    }
    x.set(key, mid);
    return mid;
  }
  for (const rel of diagram.relationships) {
    placeRelationship(rel);
  }
  for (const id of diagram.individuals.keys()) {
    if (!placed.has(id)) {
      placeNode(id);
    }
  }
  const nodeXs = Array.from(diagram.individuals.keys()).map((id) => x.get(id) ?? MARGIN_X);
  const minX = nodeXs.length > 0 ? Math.min(...nodeXs) : MARGIN_X;
  const maxX = nodeXs.length > 0 ? Math.max(...nodeXs) + SYMBOL_PX : MARGIN_X + SYMBOL_PX;
  const contentWidth = maxX - minX;
  const canvasWidth = Math.max(800, contentWidth + MARGIN_X * 2);
  const offsetX = (canvasWidth - contentWidth) / 2 - minX;
  for (const id of diagram.individuals.keys()) {
    x.set(id, (x.get(id) ?? MARGIN_X) + offsetX);
  }
  const maxLinesInRow = /* @__PURE__ */ new Map();
  for (const [id, ind] of diagram.individuals) {
    const r = row.get(id) ?? 0;
    const labelLines = ind.label ? ind.label.split("|").length : 0;
    const ageLine = ind.age ? 1 : 0;
    const totalLines = labelLines + ageLine;
    maxLinesInRow.set(r, Math.max(maxLinesInRow.get(r) ?? 0, totalLines));
  }
  const maxRow = Array.from(row.values()).reduce((max, r) => Math.max(max, r), 0);
  const rowY = /* @__PURE__ */ new Map();
  rowY.set(0, MARGIN_Y);
  for (let r = 0; r < maxRow; r++) {
    const lines = maxLinesInRow.get(r) ?? 0;
    const h = Math.max(90, SYMBOL_PX + lines * 11 + 45);
    rowY.set(r + 1, (rowY.get(r) ?? MARGIN_Y) + h);
  }
  const pos = /* @__PURE__ */ new Map();
  for (const [id, ind] of diagram.individuals) {
    pos.set(id, {
      x: x.get(id) ?? MARGIN_X,
      y: rowY.get(row.get(id) ?? 0) ?? MARGIN_Y
    });
  }
  function renderSymbol(ind, px, py) {
    const affected = ind.status === "Af";
    const carrier = ind.status === "Ca";
    const xlinked = ind.status === "XCa";
    const unknownStatus = ind.status === "Unk";
    const baseFill = affected ? theme.ink : theme.surface;
    const strokeColor = theme.ink;
    const r = SYMBOL_PX / 2;
    const groupChildren = [];
    if (ind.isMisc || ind.isInduced) {
      const points = `${r},4 ${SYMBOL_PX - 4},20 4,20`;
      groupChildren.push({
        type: "path",
        d: `M ${px + r} ${py + 4} L ${px + SYMBOL_PX - 4} ${py + 20} L ${px + 4} ${py + 20} Z`,
        fill: baseFill,
        stroke: strokeColor
      });
      if (ind.isInduced) {
        groupChildren.push({
          type: "line",
          x1: px + SYMBOL_PX - 2,
          y1: py + 2,
          x2: px + 2,
          y2: py + 22
        });
      }
    } else if (ind.isPreg || ind.sex === "U" || ind.sex === "A") {
      groupChildren.push({
        type: "path",
        d: `M ${px + r} ${py} L ${px + SYMBOL_PX} ${py + r} L ${px + r} ${py + SYMBOL_PX} L ${px} ${py + r} Z`,
        fill: baseFill,
        stroke: strokeColor
      });
      if (ind.sex === "A") {
        groupChildren.push({
          type: "text",
          x: px + r,
          y: py + r + 3,
          text: "?",
          anchor: "middle",
          fontSize: 10
        });
      } else if (ind.isPreg) {
        groupChildren.push({
          type: "text",
          x: px + r,
          y: py + r + 3,
          text: "P",
          anchor: "middle",
          fontSize: 9,
          color: affected ? theme.surface : theme.text
        });
      }
    } else if (ind.sex === "M") {
      groupChildren.push({
        type: "rect",
        x: px,
        y: py,
        width: SYMBOL_PX,
        height: SYMBOL_PX,
        fill: baseFill,
        stroke: strokeColor
      });
    } else {
      groupChildren.push({
        type: "circle",
        cx: px + r,
        cy: py + r,
        r,
        fill: baseFill,
        stroke: strokeColor
      });
    }
    if (carrier && !affected) {
      if (ind.sex === "M") {
        groupChildren.push({
          type: "rect",
          x: px,
          y: py,
          width: r,
          height: SYMBOL_PX,
          fill: theme.ink
        });
      } else if (ind.sex === "F") {
        groupChildren.push({
          type: "path",
          d: `M ${px + r} ${py} A ${r} ${r} 0 0 0 ${px + r} ${py + SYMBOL_PX} Z`,
          fill: theme.ink
        });
      } else {
        groupChildren.push({
          type: "path",
          d: `M ${px + r} ${py} L ${px} ${py + r} L ${px + r} ${py + SYMBOL_PX} Z`,
          fill: theme.ink
        });
      }
    }
    if (xlinked && !affected) {
      groupChildren.push({
        type: "circle",
        cx: px + r,
        cy: py + r,
        r: 3.5,
        fill: theme.ink
      });
    }
    if (unknownStatus) {
      groupChildren.push({
        type: "text",
        x: px + r,
        y: py + r + 3,
        text: "?",
        anchor: "middle",
        fontSize: 10
      });
    }
    if (ind.isDeceased || ind.isSb) {
      groupChildren.push({
        type: "line",
        x1: px + SYMBOL_PX + 2,
        y1: py - 2,
        x2: px - 2,
        y2: py + SYMBOL_PX + 2
      });
    }
    if (ind.isSb) {
      groupChildren.push({
        type: "text",
        x: px + r,
        y: py + SYMBOL_PX + 22,
        text: "SB",
        anchor: "middle",
        fontSize: 9
      });
    }
    if (ind.adopted) {
      const bLeft = px - 6;
      const bRight = px + SYMBOL_PX + 6;
      groupChildren.push({
        type: "path",
        d: `M ${bLeft + 3} ${py} L ${bLeft} ${py} L ${bLeft} ${py + SYMBOL_PX} L ${bLeft + 3} ${py + SYMBOL_PX}`,
        fill: "none",
        stroke: strokeColor
      });
      groupChildren.push({
        type: "path",
        d: `M ${bRight - 3} ${py} L ${bRight} ${py} L ${bRight} ${py + SYMBOL_PX} L ${bRight - 3} ${py + SYMBOL_PX}`,
        fill: "none",
        stroke: strokeColor
      });
    }
    if (ind.isIndex) {
      const ax = px - 12;
      const ay = py + SYMBOL_PX + 12;
      const tx = px - 1;
      const ty = py + SYMBOL_PX - 1;
      groupChildren.push({
        type: "line",
        x1: ax,
        y1: ay,
        x2: tx,
        y2: ty
      });
      groupChildren.push({
        type: "path",
        d: `M ${tx - 6} ${ty} L ${tx} ${ty} L ${tx} ${ty + 6}`,
        fill: "none",
        stroke: strokeColor
      });
    }
    let currentY = py + SYMBOL_PX + 11;
    if (ind.label) {
      const labelLines = ind.label.split("|");
      for (const lineText of labelLines) {
        groupChildren.push({
          type: "text",
          x: px + r,
          y: currentY,
          text: lineText,
          anchor: "middle",
          fontSize: 9
        });
        currentY += 11;
      }
    }
    if (ind.age) {
      groupChildren.push({
        type: "text",
        x: px + r,
        y: currentY,
        text: ind.age,
        anchor: "middle",
        fontSize: 9
      });
    }
    return { type: "group", x: 0, y: 0, children: groupChildren };
  }
  for (const [id, ind] of diagram.individuals) {
    const p = pos.get(id);
    nodes.push(renderSymbol(ind, p.x, p.y));
  }
  const generations = Array.from(new Set(row.values())).sort((a, b) => a - b);
  const roman = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"];
  for (let idx = 0; idx < generations.length; idx++) {
    const genY = (rowY.get(generations[idx]) ?? MARGIN_Y) + SYMBOL_PX / 2;
    nodes.push({
      type: "text",
      x: 20,
      y: genY + 3,
      text: roman[generations[idx]] || (generations[idx] + 1).toString(),
      anchor: "start",
      fontSize: 12
    });
  }
  const SIB_BAR_DROP_PX = ROW_HEIGHT_PX / 2;
  for (const rel of diagram.relationships) {
    const a = pos.get(rel.parent1);
    const b = pos.get(rel.parent2);
    const [left, right] = a.x <= b.x ? [a, b] : [b, a];
    const marriageY = left.y + SYMBOL_PX / 2;
    if (rel.op === "=") {
      nodes.push({
        type: "line",
        x1: left.x + SYMBOL_PX,
        y1: marriageY - 2,
        x2: right.x,
        y2: marriageY - 2
      });
      nodes.push({
        type: "line",
        x1: left.x + SYMBOL_PX,
        y1: marriageY + 2,
        x2: right.x,
        y2: marriageY + 2
      });
    } else {
      nodes.push({
        type: "line",
        x1: left.x + SYMBOL_PX,
        y1: marriageY,
        x2: right.x,
        y2: marriageY
      });
      const midX2 = (left.x + SYMBOL_PX + right.x) / 2;
      if (rel.op === "/") {
        nodes.push({ type: "line", x1: midX2 - 4, y1: marriageY + 5, x2: midX2, y2: marriageY - 5 });
        nodes.push({ type: "line", x1: midX2, y1: marriageY + 5, x2: midX2 + 4, y2: marriageY - 5 });
      } else if (rel.op === "|") {
        nodes.push({ type: "line", x1: midX2 - 2, y1: marriageY + 5, x2: midX2 + 2, y2: marriageY - 5 });
      }
    }
    const midX = (left.x + SYMBOL_PX + right.x) / 2;
    if (rel.isChildless) {
      const dropY = marriageY + 15;
      nodes.push({ type: "line", x1: midX, y1: marriageY, x2: midX, y2: dropY });
      nodes.push({ type: "line", x1: midX - 6, y1: dropY, x2: midX + 6, y2: dropY });
      if (rel.isInfertile) {
        nodes.push({ type: "line", x1: midX - 6, y1: dropY + 3, x2: midX + 6, y2: dropY + 3 });
      }
      continue;
    }
    if (rel.children.length === 0)
      continue;
    const parentRow = row.get(rel.parent1) ?? 0;
    const childRowY = rowY.get(parentRow + 1) ?? left.y + 90;
    const barY = childRowY - 25;
    const childDrops = [];
    for (const group of rel.children) {
      if (group.type === "single") {
        const k = pos.get(group.name);
        const ind = diagram.individuals.get(group.name);
        const dash = ind?.adopted === "out" ? "4" : void 0;
        childDrops.push({ cx: k.x + SYMBOL_PX / 2, cy: k.y, isTwin: false, strokeDash: dash });
      } else {
        const twinCenters = group.children.map((name) => pos.get(name).x + SYMBOL_PX / 2);
        const twinMidX = (Math.min(...twinCenters) + Math.max(...twinCenters)) / 2;
        for (let i = 0; i < group.children.length; i++) {
          const name = group.children[i];
          const k = pos.get(name);
          const ind = diagram.individuals.get(name);
          const dash = ind?.adopted === "out" ? "4" : void 0;
          nodes.push({
            type: "line",
            x1: twinMidX,
            y1: barY,
            x2: k.x + SYMBOL_PX / 2,
            y2: k.y,
            strokeDash: dash
          });
        }
        if (group.type === "monozygotic" && group.children.length >= 2) {
          const k1 = pos.get(group.children[0]);
          const k2 = pos.get(group.children[1]);
          const halfX1 = (twinMidX + k1.x + SYMBOL_PX / 2) / 2;
          const halfX2 = (twinMidX + k2.x + SYMBOL_PX / 2) / 2;
          const halfY = (barY + k1.y) / 2;
          nodes.push({
            type: "line",
            x1: halfX1,
            y1: halfY,
            x2: halfX2,
            y2: halfY
          });
        }
        childDrops.push({ cx: twinMidX, cy: barY, isTwin: true });
      }
    }
    nodes.push({ type: "line", x1: midX, y1: marriageY, x2: midX, y2: barY });
    const dropXs = childDrops.map((d) => d.cx);
    const minDropX = Math.min(midX, ...dropXs);
    const maxDropX = Math.max(midX, ...dropXs);
    nodes.push({ type: "line", x1: minDropX, y1: barY, x2: maxDropX, y2: barY });
    for (const drop of childDrops) {
      if (!drop.isTwin) {
        nodes.push({
          type: "line",
          x1: drop.cx,
          y1: barY,
          x2: drop.cx,
          y2: drop.cy,
          strokeDash: drop.strokeDash
        });
      }
    }
  }
  let legendY = (rowY.get(generations.length) ?? rowY.get(generations.length - 1) + 100) + 20;
  if (diagram.legends.length > 0) {
    nodes.push({
      type: "line",
      x1: MARGIN_X,
      y1: legendY,
      x2: canvasWidth - MARGIN_X,
      y2: legendY
    });
    legendY += 15;
    let lx = MARGIN_X;
    for (const leg of diagram.legends) {
      const legText = `${leg.status}: ${leg.description}`;
      if (leg.status === "XCa") {
        nodes.push({
          type: "circle",
          cx: lx + 6,
          cy: legendY + 6,
          r: 6,
          fill: theme.surface,
          stroke: theme.ink
        });
        nodes.push({
          type: "circle",
          cx: lx + 6,
          cy: legendY + 6,
          r: 2,
          fill: theme.ink,
          stroke: "none"
        });
      } else {
        const indicatorFill = leg.status === "Af" ? theme.ink : theme.surface;
        nodes.push({
          type: "rect",
          x: lx,
          y: legendY,
          width: 12,
          height: 12,
          fill: indicatorFill,
          stroke: theme.ink
        });
        if (leg.status === "Ca") {
          nodes.push({
            type: "rect",
            x: lx,
            y: legendY,
            width: 6,
            height: 12,
            fill: theme.ink
          });
        }
        if (leg.status === "Unk") {
          nodes.push({
            type: "text",
            x: lx + 6,
            y: legendY + 9,
            text: "?",
            anchor: "middle",
            fontSize: 8
          });
        }
      }
      nodes.push({
        type: "text",
        x: lx + 18,
        y: legendY + 10,
        text: leg.description,
        anchor: "start",
        fontSize: 9
      });
      lx += 150;
      if (lx > canvasWidth - 100) {
        lx = MARGIN_X;
        legendY += 20;
      }
    }
    legendY += 20;
  }
  const finalHeight = legendY + MARGIN_Y;
  return {
    width: canvasWidth,
    height: finalHeight,
    nodes
  };
}

// ../src/renderer.ts
function renderNode(node) {
  switch (node.type) {
    case "line": {
      const dash = node.strokeDash ? ` stroke-dasharray="${node.strokeDash}"` : "";
      return `<line x1="${node.x1}" x2="${node.x2}" y1="${node.y1}" y2="${node.y2}" stroke="${theme.ink}" stroke-width="1.5"${dash} />`;
    }
    case "rect":
      return `<rect x="${node.x}" y="${node.y}" width="${node.width}" height="${node.height}" fill="${node.fill ?? theme.surface}" stroke="${node.stroke ?? theme.ink}" stroke-width="1.5" />`;
    case "text":
      return `<text x="${node.x}" y="${node.y}" text-anchor="${node.anchor ?? "start"}" alignment-baseline="${node.baseline ?? "alphabetic"}" font-family="system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif" font-size="${node.fontSize ?? 10}" fill="${node.color ?? theme.text}">${node.text}</text>`;
    case "circle":
      return `<circle cx="${node.cx}" cy="${node.cy}" r="${node.r}" fill="${node.fill ?? theme.surface}" stroke="${node.stroke ?? theme.ink}" stroke-width="1.5" />`;
    case "path":
      return `<path d="${node.d}" fill="${node.fill ?? "none"}" stroke="${node.stroke ?? theme.ink}" stroke-width="1.5" />`;
    case "group":
      return `<g transform="translate(${node.x},${node.y})">
        ${node.children.map(renderNode).join("")}
      </g>`;
    default:
      return "";
  }
}
function renderSVG(layout) {
  return `<svg viewBox="0 0 ${layout.width} ${layout.height}" width="100%" style="max-width:${layout.width}px; background-color:${theme.surface};" xmlns="http://www.w3.org/2000/svg">
    ${layout.nodes.map(renderNode).join("")}
  </svg>`;
}

// ../src/index.ts
function renderPedigree(dsl) {
  const diagram = parseDSL(dsl);
  const layout = layoutDiagram(diagram);
  return renderSVG(layout);
}

// main.ts
var PedigremPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerMarkdownCodeBlockProcessor("pedigrem", (source, el, ctx) => {
      try {
        const svg = renderPedigree(source);
        const container = el.createDiv({ cls: "pedigrem-svg-container" });
        container.innerHTML = svg;
        const svgEl = container.querySelector("svg");
        if (svgEl) {
          svgEl.style.display = "block";
          svgEl.style.margin = "0 auto";
          svgEl.style.maxWidth = "100%";
        }
      } catch (e) {
        const errorDiv = el.createDiv({ cls: "pedigrem-error-container" });
        errorDiv.setText("Pedigrem render error: " + e.message);
        errorDiv.style.color = "var(--text-error, #f43f5e)";
        errorDiv.style.fontFamily = "monospace";
        errorDiv.style.padding = "8px";
        errorDiv.style.backgroundColor = "var(--background-secondary)";
        errorDiv.style.borderLeft = "4px solid var(--text-error, #f43f5e)";
        errorDiv.style.borderRadius = "4px";
      }
    });
  }
};
